// Shared project list for the desktop and phone pages.
window.PROJECTS = [
  { id: 'outlook', title: 'BrightVine Outlook Integration', kind: 'Software', year: '2025', meta: 'BrightVine Solutions', desc: 'Add a short description: what the add-in does, who uses it, and the part you owned.', tags: ['Outlook add-in', 'BrightVine'], phLabel: 'add-in screenshot' },
  { id: 'snapshot', title: 'Snapshot', kind: 'Software', year: '2025', meta: 'BrightVine Solutions', desc: 'Add a short description of Snapshot and your role on it.', tags: ['BrightVine'], phLabel: 'Snapshot screenshot' },
  { id: 'gainz', title: 'Gainz: The Financial Literacy Game', kind: 'Game', year: '2024', meta: 'Team lead + programmer, team of 5', img: 'img/gainz_logo_large.png', contain: true, desc: 'Gainz is an educational game about financial literacy. It was created in for a non-profit educational organization, Katabasis, in 2024. I worked with a team of 5 as the team lead and programmer.', tags: ['Katabasis', 'Team lead', 'Educational'], link: 'https://bbutterscotch.itch.io/gainz' },
  { id: 'pollenation', title: 'Pollenation', kind: 'Game', jam: true, year: '2024', meta: 'GMTK Jam, main programmer', img: 'img/pollenation.png', desc: 'Pollenation is a beehive simulation game where the player controls a hive of bees through resource tiles. It was created for GMTK Jam 2024, but was not finished in the given 72 hours. I worked on a team of 4 as the main programmer.', tags: ['GMTK Jam 2024', 'Team of 4', 'Simulation'], link: 'https://xinmi.itch.io/pollenation' },
  { id: 'cats', title: "Cat's Cradle", kind: 'Game', jam: true, year: '2023', meta: 'GMTK Jam, programmer', img: 'img/cats_cradle.png', pixel: true, desc: "Cat's Cradle is a tile-based puzzle game where the player tries to rid its home of pesky dogs. It was created for GMTK Jam 2023 and made in 48 hours. I worked with a team of 6 as a programmer.", tags: ['GMTK Jam 2023', '48 hours', 'Puzzle'], link: 'https://xinmi.itch.io/cats-cradle' },
  { id: 'javabean', title: 'JavaBean', kind: 'Software', year: '2023', meta: 'Lead UX + front end', img: 'img/baristaHome.png', desc: 'JavaBean is a project I worked on as a front-end developer in a software engineering class in 2023. As the lead UX designer, I overhauled the original design, came up with wireframes for all the usecases, and implemented the design using Bootstrap and AngularJS.', tags: ['AngularJS', 'Bootstrap', 'UX'] },
  { id: 'resource', title: 'Resource Rush', kind: 'Game', year: '2023', meta: 'Unity port, features + art', img: 'img/resourcerush.png', desc: 'Resource Rush is an educational farming game created in Unity in 2023. I converted the project from a javascript-based game to a Unity one and added features and art.', tags: ['Unity', 'Educational'] },
  { id: 'winter', title: 'Winter Break', kind: 'Game', year: '2023', meta: 'Class project, programmer', img: 'img/winterbreak.png', desc: 'Winter Break is a puzzle adventure game where the player is trapped in a snowglobe and must find all the pieces to escape. It was created for a class in 2023. I worked with a team of 4 as a programmer.', tags: ['Team of 4', 'Puzzle adventure'] },
  { id: 'squid', title: 'Squidnapped', kind: 'Game', year: '2023', meta: 'Solo, PuzzleScript', img: 'img/squidnapped.png', pixel: true, desc: 'Squidnapped is a game created in PuzzleScript about a squid escaping an aquarium by blocking cameras. I created it on my own for a class in 2023.', tags: ['PuzzleScript', 'Solo'], link: 'https://bbutterscotch.itch.io/squidnapped' },
  { id: 'dice', title: 'Dice Warp', kind: 'Game', jam: true, year: '2022', meta: 'GMTK Jam, solo', img: 'img/dicewarp.png', pixel: true, desc: 'Dice warp is a tile-based puzzle game built in Unity where the goal is to get the dice to the end with the correct face. I created it on my own for GMTK Jam 2022. I used outside assets for the art.', tags: ['GMTK Jam 2022', 'Unity', 'Solo'], link: 'https://bbutterscotch.itch.io/dice-warp' },
  { id: 'gods', title: "God's Year Off", kind: 'Game', jam: true, year: '2021', meta: 'GMTK Jam, solo art + code', img: 'img/gods_year_off.png', pixel: true, desc: "God's Year Off is a asteroids-style pixel art game. I created it for GMTK Jam 2021 and it was the first game I ever published. I created all of the art and programmed it on my own.", tags: ['GMTK Jam 2021', 'Pixel art', 'Solo'], link: 'https://bbutterscotch.itch.io/gods-year-off' },
];
